services:
    #app
    app:
      build:
        dockerfile: ./nginx/Dockerfile
      container_name: squirtmusic-app
      restart: always
      working_dir: /var/www/html/
      volumes:
        - ./src:/var/www/html
    # nginx
    nginx:
      image: nginx:1.26.1-alpine
      container_name: squirtmusic-nginx
      restart: always
      ports:
        - "80:80"
      volumes:
          - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    # php
    # app:
    #     image: garyclarke/php-composer:1.2
    #     environment:
    #         MYSQL_HOST: db
    #         MYSQL_PORT: ${MYSQL_PORT}
    #         MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    #         MYSQL_DATABASE: ${MYSQL_DATABASE}
    #         MYSQL_USER: ${MYSQL_USER}
    #         REDIS_HOST: cache
    #         REDIS_PORT: ${REDIS_PORT}
    #     extra_hosts:
            # Ensure that host.docker.internal is correctly defined on Linux
            # - host.docker.internal:host-gateway
    # mysql
    # db:
    #     image: mysql:8.0
    #     volumes:
    #         - mysqldata:/var/lib/mysql
    #     restart: always
    #     environment:
    #         MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    #         MYSQL_USER: ${MYSQL_USER}
    #         MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    #         MYSQL_DATABASE: ${MYSQL_DATABASE}
    # # redis
    # cache:
    #     image: redis:latest

# volumes:
#     mysqldata: